### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by anandanand84** [GoogleChrome/simplehttp2server#10]
Is there a way to add a proxy, Say if I want to proxy /api to http://localhost:8421/api to access my apis how should I do that?

**Comment by surma** [comment]
Currently, that is not possible, no. This webserver is just for playing around for HTTP/2 locally, so I don’t think I will add that feature. This would probably be done with a reverse-proxy like nginx and in that scenario it would also have to be nginx that does the HTTP/2.
