### ISSUE TITLE
HTTP -> HTTPS redirect not firing

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/simplehttp2server#16]
Sup dude,

When I hit localhost:5000 on http I don't get a redirect to https. Looks like it knows about it:

```bash
http: TLS handshake error from [::1]:61421: tls: first record does not look like a TLS handshake
```

Should I expect it to redirect?

**Comment by surma** [comment]
I forgot to update the brew formula with the last release and you are using this via brew, right? 

I updated the formula – can you retry?

**Comment by paullewis** [comment]
Aye, that's done it! 🎉
