### ISSUE TITLE
Content-Length header wrong/broken/missing/sad/depleted/ruined

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/simplehttp2server#17]
Not seeing it show up (comes through as `null` for `response.headers.get('Content-Length')`.

Switching off gzip makes it all hunky dory.

**Comment by surma** [comment]
I completely removed gzip support for now

**Comment by paullewis** [comment]
Yah booooooo. I like gzip.

**Comment by paullewis** [comment]
#supportbrotli

**Comment by surma** [comment]
The issue is mostly that I’d have to compress ahead-of-time in memory to figure out the compressed size to set `Content-Length`. Once I figure out a good way to do that, I might add it back in  ¯\_(ツ)_/¯

**Comment by surma** [comment]
It should work with streaming gzip and whitelist/blacklist to skip over media files.

**Comment by surma** [comment]
GZIP’s baaaaack! cc @jakearchibald
