### ISSUE TITLE
Warning when installing on OS X 10.12

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/simplehttp2server#18]
Warning: You are using OS X 10.12.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakages.

If I find anything broken or failing, I'll add it to this ticket.

**Comment by surma** [comment]
Are you on macOS < 10.12? And how did you install `simplehttp2server`?

**Comment by jpmedley** [comment]
So,
* Installed homebrew to ~/Homebrew instead of the default location.
* I was prompted to upgrade xcode.
The error went away.
