### ISSUE TITLE
Warning Printed to Console when Media Download Finishes

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/simplehttp2server#19]
[This code](https://github.com/jpmedley/mse/blob/master/index.html) causes the messages below to print to the console when it finishes downloading.

    disconnecting; error reading frame from client [::1]:50784: read tcp [::1]:5000->[::1]:50784: i/o timeout
    disconnecting; error reading frame from client [::1]:50787: read tcp [::1]:5000->[::1]:50787: i/o timeout

**Comment by surma** [comment]
This is fixed in 3.0 :) Before I was gzip’ing media files and because of the lack of `Content-Length` header the connection got closed by the browser ungracefully. The new version only gzip’s text-based file formats.
