### ISSUE TITLE
Patch HTTP method missing in Access-Control-Allowed-Methods header property

### ISSUE THREAD

**Issue by lozandier** [GoogleChrome/simplehttp2server#2]
## The Problem 
On [line 83](https://github.com/GoogleChrome/simplehttp2server/blob/master/simplehttp2server.go#L83) of `simplehttp2server.go` it seems `PATCH` is omitted in a context that it shouldn't.  

### Side-effect
Unless it's simply not supported as I think it is, `PATCH` being omitted can unexpectedly break the Principle of Least Astonishment when partially updating representation of resources on the server with a set of operations or the resource sent back itself.

## The Suggestion Action
If I'm correct,  Line 83 can be changed to the following:
```
w.Header().Set("Access-Control-Allow-Methods", "GET, OPTION, HEAD, PUT, PATCH, POST, DELETE")
```

**Comment by surma** [comment]
Sorry for the late reply. My emails got filtered the wrong way :confused: 

You are totally right, will fix :)
