### ISSUE TITLE
"hosting" property not handled

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/simplehttp2server#21]
simplehttp2server doesn't seem to correctly handle `firebase.json` files in cases where the `public` key is a child of the `hosting` key.

For example, this `firebase.json` [from the documentation](https://firebase.google.com/docs/hosting/full-config) is not parsed correctly:

```json
{
  "hosting": {
    "public": "app",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

(The `public` key is ignored, and `simplehttp2server` serves from the "root".)

To make it work as expected, the `public` key needs to be moved to the root:

```json
{
  "public": "app",
  "hosting": {
    "public": "app",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

**Comment by surma** [comment]
Oooh, good find! I did take care of the `hosting` key, but `public` had some special handling so that’s the odd one out. Will fix asap
