### ISSUE TITLE
Using Node/PHP/Python?

### ISSUE THREAD

**Issue by rakibtg** [GoogleChrome/simplehttp2server#24]
Ow, loving it, simple and works.. Is it possible to tell the server run the code in node/php/python?
This repository motivating me to learn Go 💯

**Comment by surma** [comment]
No, simplehttp2server does not have support for dynamic content, just static content, and that’s probably not going to change.

If you want dynamic content, may I suggest setting up Apache, Nginx or something of that sorts with HTTP/2? I totally wrote a [blog post](http://dassur.ma/things/h2setup/) on how to do that ;)

**Comment by rakibtg** [comment]
Many thanks @surma
