### ISSUE TITLE
An SSL certificate error occurred when fetching the script

### ISSUE THREAD

**Issue by pragmaproducts** [GoogleChrome/simplehttp2server#28]
There seem to be issues with loading service worker scripts using simpleHtt2server
How can one get past this?

```
An SSL certificate error occurred when fetching the script.
:5000/service-worker.js Failed to load resource: net::ERR_INSECURE_RESPONSE
(index):30 Registration failed with SecurityError: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the 
```

**Comment by surma** [comment]
This is _super_ annoying. I need to put something into my README regarding this.

Sadly, self-signed certificates won’t allow ServiceWorkers to run, _unless_ you start Chrome with the `--allow-insecure-localhost` flag.

I am working with the Chrome team to change that, but for now, it’s not possible without a command line flag :( Apologies.
