### ISSUE TITLE
Shouldn't cross compiling "go get" "github.com/NYTimes/gziphandler"?

### ISSUE THREAD

**Issue by diligiant** [GoogleChrome/simplehttp2server#29]
simplehttp2server is embedded in a number of non-go projects and using one of them today on a "virgin" environnement, I noticed crosscompile.sh failed looking for gziphandler.

So I was wondering if you shouldn't "go get" or benefit from vendoring?

**Comment by surma** [comment]
I patched that yesterday. See #27

**Comment by diligiant** [comment]
Thank you ; I guess I have to lift up the requirements of 3.1.3 ;)

**Comment by oren** [comment]
I had the same issue - https://github.com/developit/preact-cli/issues/73#issuecomment-305995923
