### ISSUE TITLE
Problem with Windows binary

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/simplehttp2server#4]
I’m on Windows 10 (build 14342). When I run the “simplehttp2server_windows_amd64” binary in the command line, I get the “How do you want to open this file?” dialog. Is this a known issue?

(I’ve downloaded the binary, renamed it to “simplehttp2server”, and moved it into one of my directories that’s in my PATH.)

**Comment by surma** [comment]
Thanks for issuing! Yes, known issue and I am to blame! Just add `.exe` to the end of the filename :) Will fix in the release section soon.

**Comment by surma** [comment]
Fix’d :)
