### ISSUE TITLE
Launch the URL.

### ISSUE THREAD

**Issue by rodrigograca31** [GoogleChrome/simplehttp2server#5]
Hi!

IMHO it should open the URL in the system default browser when it finishes "loading"...

Thanks!

**Comment by surma** [comment]
I disagree. I personally think that becomes fairly annoying really quickly, because sometimes you want the server just for your headless tests or for your non-default browser. If you want to open the browser do something like `simplehttp2server & open https://localhost:5000; fg`

**Comment by rodrigograca31** [comment]
Ok...
Your command did not work (Linux here), but this one works for me:
`xdg-open https://localhost:5000 & ./simplehttp2server_linux_amd64`
