### ISSUE TITLE
Not able to open the URL on latest version of Chrome?

### ISSUE THREAD

**Issue by rodrigograca31** [GoogleChrome/simplehttp2server#6]
Hi!

Not able to open [https://localhost:5000/](https://localhost:5000/) on chrome `Version 53.0.2767.4 dev (64-bit)` and `Version 51.0.2704.103 (64-bit)` on (Linux Mint)

Normaly I would go to the advanced option and would say something like "add exception", but it doesn't have that option... is this related to the tool or Chrome?
![image](https://cloud.githubusercontent.com/assets/1134310/16135408/56eaee70-341b-11e6-9893-ae53d7b21cd5.png)

I've also tried with [https://127.0.0.1:5000/](https://127.0.0.1:5000/) and the same happens...

It opened on Firefox.... but seriously, who uses Firefox!? :smile: (flame war started!)

Thanks!

**Comment by surma** [comment]
Sadly, I can’t reproduce :( Can you give this a try in Canary just to make sure?
Also, there’s a flag under `chrome://flags/#allow-insecure-localhost` that removes this warning altogether for localhost.

**Comment by rodrigograca31** [comment]
I'm using Canary...

It works with that flag enabled!

**Comment by surma** [comment]
<img width="877" alt="screenshot 2016-06-21 10 13 57" src="https://cloud.githubusercontent.com/assets/234957/16224974/cbe747b4-37a4-11e6-8e60-e21fe5c0db6d.png">

I have this dialog (without the flag!). Don’t know what I am doing differently here, sorry.
